server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
# 关闭自动配置启用所有请求得检测
management:
  metrics:
    web:
      server:
        auto-time-requests: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔(s)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端剔除服务的时间(s)
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
    # 从Eureka服务端获取注册信息的间隔说明(s)
    registry-fetch-interval-seconds: 10