server:
  port: 8140
  servlet:
    context-path: /user
spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:8090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔(s)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端剔除服务的时间(s)
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
    health-check-url-path: /actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
    # 从Eureka服务端获取注册信息的间隔说明(s)
    registry-fetch-interval-seconds: 10
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 3000