server:
  port: 8002
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 1000
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/