server:
  port: 8010
  servlet:
    context-path: /front-admin
spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:8090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔(s)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端剔除服务的时间(s)
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
    # 从Eureka服务端获取注册信息的间隔说明(s)
    registry-fetch-interval-seconds: 10

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000